BookShop/BookShop/Models/CheckModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookShop.Models
{
    public class CheckModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool Checked { get; set; }
    }
}

BookShop/BookShop/ViewModels/AuthorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookShop.ViewModels
{
    public class AuthorViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "The field {0} is required")]
        [Display(Name="Name")]
        public string Name { get; set; }

        public List<Book> Books { get; set; }
    }
}

BookShop/BookShop/ViewModels/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookShop.ViewModels
{
    public class BookViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Publisher")]
        public Publisher Publisher { get; set; }

        [Display(Name = "Price")]
        public double Price { get; set; }

        [Display(Name = "Date Published")]
        public System.DateTime PublishedAt { get; set; }

        public List<Author> Authors { get; set; }

    }
}

BookShop/BookShop/ViewModels/PublisherViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookShop.ViewModels
{
    public class PublisherViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Поле {0} обязательно для заполнения")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        public List<Book> Books { get; set; }
    }
}

BookShop/BookShop/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookShop.ViewModelHelpers;
using BookShop.ViewModels;
using BookShop.Services;

namespace BookShop.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author
        public ActionResult Create()
        {
            return View(AuthorViewModelHelper.PopulateAuthorViewModelHelper(new Author()));
        }

        [HttpPost]
        public ActionResult Create(AuthorViewModel model)
        {
            var author = AuthorViewModelHelper.PopulateAuthorFromEditViewModel(model);
            if (author != null)
            {
                AuthorService.Create(author);
            }
            return RedirectToAction("Index", "Book");
        }
    }
}

BookShop/BookShop/Controllers/BookController.cs
using BookShop.Services;
using BookShop.ViewModelHelpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookShop.ViewModels;

namespace BookShop.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            var books = BookViewModelHelper.PopulateBookViewModelHelperList(BookService.GetAll());
            return View(books);
        }

        public ActionResult Create()
        {
            HtmlHelper.ClientValidationEnabled = true;
            HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
            var model = new BookEditViewModel();
            var authors = AuthorService.GetAll();
            BookEditViewModelHelper.PopulateAuthorCheckList(model, authors);
            var publishers = PublisherService.GetAll();
            BookEditViewModelHelper.PopulatePublisherList(model, publishers);
            model.PublishedAt = DateTime.Now;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(BookEditViewModel model)
        {
            TempData["model"] = model;
            return RedirectToAction("Confirm");
        }

        public ActionResult Details(int bookId)
        {
            var book = BookService.Get(bookId);
            if (book != null)
            {
                var model = BookEditViewModelHelper.PopulateBookEditViewModel(book);
                var authors = AuthorService.GetAll();
                BookEditViewModelHelper.PopulateAuthorCheckList(model, authors);
                var publishers = PublisherService.GetAll();
                BookEditViewModelHelper.PopulatePublisherList(model, publishers);
                return View(model);
            }
            return RedirectToRoute("Index", "Book");
        }
        
        public ActionResult Confirm()
        {
            var model = (BookEditViewModel)TempData["model"];
            var publishers = PublisherService.GetAll();
            BookEditViewModelHelper.PopulatePublisherList(model, publishers);
            return View(model);
        }
        [HttpPost]
        public ActionResult Confirm(BookEditViewModel model)
        {
            Book book = BookEditViewModelHelper.PopulateBookFromEditViewModel(model);
            BookService.Create(book);
            return RedirectToAction("Index");
        }
    }
}

BookShop/BookShop/Views/Book/Confirm.cshtml
@model BookShop.ViewModels.BookEditViewModel

@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Details book</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdPublisher)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdPublisher,
                                           Model.SelectPublisher,
                                           "Select publisher", new { @disabled = "disabled" })
            @Html.HiddenFor(Model => Model.IdPublisher)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name, new { @disabled = "disabled" })
            @Html.HiddenFor(Model => Model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Description, new { @disabled = "disabled" })
            @Html.HiddenFor(Model => Model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Price, new { type = "number", @disabled = "disabled" })
            @Html.HiddenFor(Model => Model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PublishedAt)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PublishedAt, new { type = "date", @disabled = "disabled" })
            @Html.HiddenFor(Model => Model.PublishedAt)
        </div>
        <fieldset>
            <legend>Автор</legend>
            @for (int i = 0; i < Model.CheckAuthor.Count; i++)
            {
                @Html.CheckBoxFor(Model => Model.CheckAuthor[i].Checked, new { @disabled = "disabled" })
                @Html.HiddenFor(Model => Model.CheckAuthor[i].Id)
                @Html.HiddenFor(Model => Model.CheckAuthor[i].Name)
                @Html.Label(Model.CheckAuthor[i].Name)
                <br />
            }
        </fieldset>
    </fieldset>
    <p>Save Data?</p>
    <p>
        <input type="submit" value="Yes" />
        @Html.ActionLink("No", "Index")
    </p>
}

BookShop/BookShop/Views/Book/Details.cshtml
@model BookShop.ViewModels.BookEditViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Details book</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdPublisher)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdPublisher,
                                           Model.SelectPublisher,
                                           "Select publisher", new { @disabled = "disabled" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">

            @Html.HiddenFor(Model => Model.Name)
            @Html.TextBoxFor(model => model.Name, new { @disabled = "disabled" })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">

            @Html.HiddenFor(Model => Model.Description)
            @Html.TextBoxFor(model => model.Description,new { @disabled = "disabled" })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">

            @Html.HiddenFor(Model => Model.Price)
            @Html.TextBoxFor(model => model.Price, new { type = "number", @disabled = "disabled" })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PublishedAt)
        </div>
        <div class="editor-field">
            @Html.EditorFor(Model=>Model.PublishedAt,new { type="date", @disabled = "disabled" })
                @Html.HiddenFor(Model=>Model.PublishedAt)
         </div>
        <fieldset>
            <legend>Автор</legend>
            @for (int i = 0; i < Model.CheckAuthor.Count; i++)
            {
                @Html.CheckBoxFor(Model => Model.CheckAuthor[i].Checked, new { @disabled = "disabled" })
                @Html.HiddenFor(Model => Model.CheckAuthor[i].Id)
                @Html.Label(Model.CheckAuthor[i].Name)
                <br />
            }
        </fieldset>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookShop/BookShop/Views/Book/Index.cshtml
@model IEnumerable<BookShop.ViewModels.BookViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}

<h2>Книги</h2>

<table id="table">
    <tr>
        <th>
           Автор
        </th>
        <th>
            @Html.LabelFor(model => model.First().Name)
        </th>
        <th>
            @Html.LabelFor(model => model.First().Publisher.Name)
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @foreach (var item2 in item.Authors)
                { 
                    @Html.Label(item2.Name)
                    <br/>
                }
            </td>
            <td>
                @Html.Label(item.Name)
            </td>
            <td>
                @Html.Label(item.Publisher.Name)
              </td>
            <td>
                @Html.ActionLink("Details", "Details", new { bookId = item.Id })
            </td>
        </tr>
    }
</table>

BookShop/BookShop/Views/Publisher/Create.cshtml
@model BookShop.ViewModels.PublisherViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Create new Publisher</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name)
            @Html.ValidationMessageFor(model=>model.Name)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookShop/BookShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Книжный магазин</title>
    <link href="~/Content/MyStyle.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-2.1.4.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="container">
        <div id="header">
            BookShop
        </div>
        <div id="sidebar">
            @Html.Partial("_NavBarPartial")
        </div>
        <div id="content">
            @RenderBody()
        </div>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

BookShop/BookShop/Views/Shared/_NavBarPartial.cshtml
<div id="partial2">
    <ul id="navbar">
        <li>
            @Html.ActionLink("Main", "Index", "Book", new { area = "" }, null)
        </li>
        <li>
            @Html.ActionLink("Create Book", "Create", "Book", new { area = "" }, null)
        </li>
        <li>
            @Html.ActionLink("Create Publisher", "Create", "Publisher", new { area = "" }, null)
        </li>
        <li>
            @Html.ActionLink("Create Author", "Create", "Author", new { area = "" }, null)
        </li>
    </ul>
</div>